### ISSUE TITLE
How to train models using other datasets, such as GSM-8K

### ISSUE THREAD

**Issue by qxpBlog** [Pengxin-Guo/FedSA-LoRA#2]
Sorry,When I tried to train my model using a different dataset, the following error occurred：
```
Traceback (most recent call last):
  File "FedSA-LoRA/federatedscope/main.py", line 67, in <module>
    _ = runner.run()
  File "FedSA-LoRA/federatedscope/core/fed_runner.py", line 401, in run
    self._run_simulation()
  File "FedSA-LoRA/federatedscope/core/fed_runner.py", line 484, in _run_simulation
    self._handle_msg(msg)
  File "FedSA-LoRA/federatedscope/core/fed_runner.py", line 425, in _handle_msg
    self.client[each_receiver].msg_handlers[msg.msg_type](msg)
  File "FedSA-LoRA/federatedscope/core/workers/client.py", line 348, in callback_funcs_for_model_para
    sample_size, model_para_all, results = self.trainer.train()
  File "FedSA-LoRA/federatedscope/core/auxiliaries/decorators.py", line 7, in wrapper
    num_samples_train, model_para, result_metric = func(
  File "FedSA-LoRA/federatedscope/core/trainers/trainer.py", line 238, in train
    num_samples = self._run_routine(MODE.TRAIN, hooks_set,
  File "FedSA-LoRA/federatedscope/core/trainers/context.py", line 345, in wrapper
    res = func(self, mode, hooks_set, dataset_name)
  File "FedSA-LoRA/federatedscope/core/trainers/trainer.py", line 274, in _run_routine
    self._run_epoch(hooks_set)
  File "FedSA-LoRA/federatedscope/core/trainers/context.py", line 364, in wrapper
    res = func(self, *args, **kwargs)
  File "FedSA-LoRA/federatedscope/core/trainers/trainer.py", line 291, in _run_epoch
    self._run_batch(hooks_set)
  File "FedSA-LoRA/federatedscope/core/trainers/context.py", line 364, in wrapper
    res = func(self, *args, **kwargs)
  File "FedSA-LoRA/federatedscope/core/trainers/trainer.py", line 307, in _run_batch
    hook(self.ctx)
  File "FedSA-LoRA/federatedscope/glue/trainer/trainer.py", line 83, in _hook_on_batch_forward
    labels = ctx.data_batch['label'].to(ctx.device)
KeyError: 'label'
```

**Comment by qxpBlog** [comment]
@Pengxin-Guo. Sorry, how can i solve this problem.

**Comment by Pengxin-Guo** [comment]
This error is due to the absence of a 'label' key in the GSM-8K dataset. 
You can use the command 
`python federatedscope/main.py --cfg federatedscope/llm/yamls/fedsa-lora.yaml 
`
to train a model on the GSM-8K dataset.

**Comment by qxpBlog** [comment]
> This error is due to the absence of a 'label' key in the GSM-8K dataset. You can use the command `python federatedscope/main.py --cfg federatedscope/llm/yamls/fedsa-lora.yaml ` to train a model on the GSM-8K dataset.

Thanks!
